# <------- Site settings ------->
title: Sheep's Blog
SEOTitle: 肥羊博客 | Sheep's Blog
header-img: img/home-bg.jpg
email: yushuaikiwi@gmail.com
description: "菜鸡的自留地233333"
keyword: "博客, 个人网站, 互联网"
url: ""              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# <------- SNS settings ------->
RSS: false
# weibo_username:     id
# zhihu_username:     id
# github_username:    id
# twitter_username:   id
# facebook_username:  id
# linkedin_username:  firstname-lastname-idxxxx


# <------- Build settings ------->
highlighter: rouge # from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true 
# if you want to customize anchor. check out line:181 of `post.html`

timezone: CN  


# Gems
# to support local preview for Jekyll 3.0

plugins: [jekyll-paginate] # make sure you have this gem installed `$ gem install jekyll-paginate`


# <------- Markdown settings ------->
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1


# <------- Disqus settings ------->
#disqus_username: 

# <------- Netease settings ------->
netease_comment: false


# Analytics settings ------->
# Baidu Analytics 
# ba_track_id: [your track id]
# Google Analytics
#ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
#ga_domain: huangxuan.me


# <------- Sidebar settings ------->
sidebar: true                           # whether or not using sidebar. Without sidebar, short about won't show.
sidebar-about-description: "Fat Sheep, going deep, don't be afraid to make a leap"
# sidebar-avatar: /img/avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value


# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true


# MathJax rendering or not for layout:page (e.g. post preview)
page-mathjax: false


# Friends move it out to data
friends: [
    {
        title: "DHong Say",
        href: "http://dhong.co"
    }
    # ,{
    #     title: "尹峰以为",
    #     href: "http://ingf.github.io/"
    # }
]
